language: java
sudo: false
#jdk: oraclejdk12
#install: true
#script: mvn clean compile assembly:single
cache:
  directories:
    - $HOME/.m2

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "pre alation"
  env: "PreAlation-env-docker"
  bucket_name: "elasticbeanstalk-us-east-2-202443327350"
  bucket_path: "pre-alation-docker"
  artifact: true
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"