language: java
sudo: false
services: docker

#before_install:

cache:
  directories:
    - $HOME/.m2

deploy:
  script:
    - docker-compose build
    - docker-compose up -d
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "pre alation"
  env: "PreAlation-env-docker"
  bucket_name: "elasticbeanstalk-us-east-2-202443327350"
  bucket_path: "pre-alation-docker"
  artifact: true
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"